### ISSUE TITLE
Initial Release

### ISSUE THREAD

**Issue by prologic** [prologic/charla#1]
# Plan for Initial Public Release

See: [0.1 - Public Release](https://github.com/prologic/charla/milestones/0.1)
## Core
- [x] Basic connectvity
- [x] Basic channel support
- [x] Basic messaging support
- [x] Validate valid nick characters
- [x] Validate valid channel name characters
- [x] Restrict nick length (_and advertise_)
- [x] Restrict channel name length  (_and advertise_)
- [x] Restrict topic length (_and advertise_)
- [ ] Restrict no. of mode changes (_and advertise_)
- [x] Timeout dead clients
## Commands
- [x] JOIN
- [x] MODE
- [x] NICK
- [x] NOTICE
- [x] PART
- [x] PING
- [x] PONG
- [x] PRIVMSG
- [x] AWAY
- [x] QUIT
- [x] USER
- [x] WHO
- [x] NAMES
- [x] KICK
- [x] LIST
- [x] OPER
- [x] KILL
- [x] RESTART
- [x] DIE
- [x] LUSERS
- [x] MOTD
- [x] TOPIC
- [x] WHOIS
- [x] VERSION
- [x] LOAD (_1_)
- [x] UNLOAD (_2_)
- [x] RELOAD (_3_)
## Channel Modes
- [x] `+o` operator
- [x] `+v` voice
- [x] `+t` topic protection
- [x] `+n` no external messages
- [x] `+m` moderated
- [ ] `+b` user ban(s)
## User Modes
- [x] `+i` invisible
- [x] `+o` operator
## Server Numerics
- [x] `001` welcome
- [x] `002` host information
- [x] `003` server creation data
- [x] `004` server version
- [x] `005` supported features
## Server Settings/Features
- [x] `PREFIX`
- [x] `CHANTYPES`
- [x] `NICKLEN`
- [x] `CHANNELLEN`
- [x] `TOPICLEN`
- [x] `CHANLIMIT`

---
1. Invented command to load plugins. Syntax: `LOAD <plugin>`
2. Invented command to unload plugins. Syntax: `UNLOAD <plugin>`
3. Invented command to reload plugins. Syntax: `RELOAD <plugin>`
##

**Comment by prologic** [comment]
- [ ] Fix multiple channel/user modes

**Comment by prologic** [comment]
- [ ] Rework admin/processor (_reloading them doesn't work_)

**Comment by prologic** [comment]
- [x] Fix hostmasks. `Romster@::ffff:202.168.100.149` (_for example_) breaks `/WHO` parsing on clients

**Comment by prologic** [comment]
- [x] Fix the IRC protocol parser in circuits to tolerate bad input.

I've seen bad input such at `\n` whereby this happens:

```
2015-08-30 14:56:05,210 - charla.main - DEBUG - <read[server] (<socket._socketobject object at 0x7f30280a5bb0>, 'USER foo x x :foo\r\nNICK foo\r\n\n' )>
2015-08-30 14:56:05,210 - plugins.Debug - INFO - I: [::ffff:127.0.0.1:45333] 'USER foo x x :foo\r\nNICK foo\r\n\n'
2015-08-30 14:56:05,211 - charla.main - DEBUG - <write[server] (<socket._socketobject object at 0x7f30280a5bb0>, ':daisy.shortcircuit.net.au NOTICE * :*** Looking up your hostname...\r\n' )>
2015-08-30 14:56:05,212 - plugins.Debug - INFO - O: [::ffff:127.0.0.1:45333] ':daisy.shortcircuit.net.au NOTICE * :*** Looking up your hostname...\r\n'
2015-08-30 14:56:05,212 - charla.main - DEBUG - <line[server] (<socket._socketobject object at 0x7f30280a5bb0>, 'USER foo x x :foo' )>
2015-08-30 14:56:05,212 - charla.main - DEBUG - <line[server] (<socket._socketobject object at 0x7f30280a5bb0>, 'NICK foo' )>
2015-08-30 14:56:05,212 - charla.main - DEBUG - <line[server] (<socket._socketobject object at 0x7f30280a5bb0>, '' )>
2015-08-30 14:56:05,213 - charla.main - DEBUG - <user[server] (<socket._socketobject object at 0x7f30280a5bb0>, (u'', None, None), u'foo', u'x', u'x', u'foo' )>
2015-08-30 14:56:05,213 - charla.main - DEBUG - <nick[server] (<socket._socketobject object at 0x7f30280a5bb0>, (u'', None, None), u'foo' )>
2015-08-30 14:56:05,214 - charla.main - DEBUG - <exception[*] (<type 'exceptions.IndexError'>, IndexError('pop from empty list',), ['  File "/home/prologic/circuits/circuits/core/manager.py", line 681, in _dispatcher\n    value = event_han
2015-08-30 14:56:05,214 - charla.main - ERROR - ERROR <handler[*][line] (IRC.line)> (<line[server] (<socket._socketobject object at 0x7f30280a5bb0>, '' )>) (<type 'exceptions.IndexError'>): IndexError('pop from empty list',)
Traceback (most recent call last):
  File "/home/prologic/circuits/circuits/core/manager.py", line 681, in _dispatcher
    value = event_handler(*eargs, **ekwargs)
  File "/home/prologic/circuits/circuits/protocols/irc/protocol.py", line 55, in line
    prefix, command, args = parsemsg(line, encoding=self.encoding)
  File "/home/prologic/circuits/circuits/protocols/irc/utils.py", line 94, in parsemsg
    command = str(args.pop(0))
IndexError: pop from empty list
```

**Comment by prologic** [comment]
- [ ] Fix `--embedded` mode and Redisco so that Redislite is used in this mode regardless of whether `redis` is importable or not.
